apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  labels:
    app: webmethods
    app.kubernetes.io/instance: webmethods
  name: webmethods
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webmethods
    deploymentconfig: webmethods
  sessionAffinity: None
  type: ClusterIP


